package com.example.rentals.scheduler;

import com.example.rentals.booking.Booking;
import com.example.rentals.booking.BookingRepository;
import com.example.rentals.booking.BookingStatus;
import com.example.rentals.booking.BookingStatusHistory;
import com.example.rentals.booking.BookingStatusHistoryRepository;
import com.example.rentals.notification.NotificationType;
import com.example.rentals.notification.event.BookingEvent;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.Lazy;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

@Slf4j
@Component
public class CompleteStayJob {

    private final BookingRepository bookingRepository;
    private final BookingStatusHistoryRepository bookingStatusHistoryRepository;
    private final ApplicationEventPublisher eventPublisher;
    private final Clock clock;
    private final CompleteStayJob self;

    /**
     * Written out rather than generated by Lombok so {@code @Lazy} is guaranteed to land on
     * the parameter: without the lazy proxy this is a bean cycle, and without the proxy
     * {@code this.completeStay(...)} would silently bypass {@code @Transactional}.
     */
    public CompleteStayJob(BookingRepository bookingRepository,
                           BookingStatusHistoryRepository bookingStatusHistoryRepository,
                           ApplicationEventPublisher eventPublisher,
                           Clock clock,
                           @Lazy CompleteStayJob self) {
        this.bookingRepository = bookingRepository;
        this.bookingStatusHistoryRepository = bookingStatusHistoryRepository;
        this.eventPublisher = eventPublisher;
        this.clock = clock;
        this.self = self;
    }

    @Scheduled(fixedRate = 900000)
    public void run() {
        Instant now = clock.instant();
        LocalDate todayUtc = LocalDate.ofInstant(now, ZoneId.of("UTC"));
        List<Booking> candidates = bookingRepository.findCompletedStaysCandidates(todayUtc);

        for (Booking candidate : candidates) {
            try {
                ZoneId listingTz = ZoneId.of(candidate.getListingTimezone());
                LocalDate localToday = LocalDate.ofInstant(now, listingTz);
                if (!localToday.isBefore(candidate.getCheckOut())) {
                    self.completeStay(candidate.getId(), now);
                }
            } catch (Exception e) {
                log.error("Failed to complete stay for booking id={}: {}", candidate.getId(), e.getMessage());
            }
        }
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void completeStay(Long bookingId, Instant now) {
        Booking b = bookingRepository.findByIdForUpdate(bookingId).orElse(null);
        if (b == null) return;

        if (b.getStatus() == BookingStatus.CONFIRMED) {
            b.transitionTo(BookingStatus.COMPLETED, null);
            b.setCompletedAt(now);
            bookingRepository.save(b);

            BookingStatusHistory history = new BookingStatusHistory(
                    b, BookingStatus.CONFIRMED.name(), BookingStatus.COMPLETED.name(), null, "SYSTEM", "Stay completed automatically");
            bookingStatusHistoryRepository.save(history);

            eventPublisher.publishEvent(new BookingEvent(bookingId, NotificationType.BOOKING_COMPLETED));
            log.info("Booking id={} transitioned to COMPLETED", bookingId);
        }
    }
}
