package com.example.rentals.scheduler;

import com.example.rentals.booking.Booking;
import com.example.rentals.booking.BookingRepository;
import com.example.rentals.booking.BookingStatus;
import com.example.rentals.booking.BookingStatusHistory;
import com.example.rentals.booking.BookingStatusHistoryRepository;
import com.example.rentals.notification.NotificationType;
import com.example.rentals.notification.event.BookingEvent;
import com.example.rentals.payment.Payment;
import com.example.rentals.payment.PaymentRepository;
import com.example.rentals.payment.PaymentStatus;
import com.example.rentals.payment.RefundReason;
import com.example.rentals.payment.RefundService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.Lazy;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.util.List;

@Slf4j
@Component
public class ExpirePendingPaymentJob {

    private final BookingRepository bookingRepository;
    private final BookingStatusHistoryRepository bookingStatusHistoryRepository;
    private final PaymentRepository paymentRepository;
    private final RefundService refundService;
    private final ApplicationEventPublisher eventPublisher;
    private final Clock clock;
    private final ExpirePendingPaymentJob self;

    /**
     * Written out rather than generated by Lombok so {@code @Lazy} is guaranteed to land on
     * the parameter: without the lazy proxy this is a bean cycle, and without the proxy
     * {@code this.expireHold(...)} would silently bypass {@code @Transactional} and fail with
     * "Query requires transaction be in progress".
     */
    public ExpirePendingPaymentJob(BookingRepository bookingRepository,
                                   BookingStatusHistoryRepository bookingStatusHistoryRepository,
                                   PaymentRepository paymentRepository,
                                   RefundService refundService,
                                   ApplicationEventPublisher eventPublisher,
                                   Clock clock,
                                   @Lazy ExpirePendingPaymentJob self) {
        this.bookingRepository = bookingRepository;
        this.bookingStatusHistoryRepository = bookingStatusHistoryRepository;
        this.paymentRepository = paymentRepository;
        this.refundService = refundService;
        this.eventPublisher = eventPublisher;
        this.clock = clock;
        this.self = self;
    }

    @Scheduled(fixedRate = 60000)
    public void run() {
        Instant now = clock.instant();
        List<Booking> expiredHolds = bookingRepository.findExpiredHolds(now);
        if (expiredHolds.isEmpty()) return;

        log.info("ExpirePendingPaymentJob found {} holds to expire", expiredHolds.size());
        for (Booking hold : expiredHolds) {
            try {
                self.expireHold(hold.getId(), now);
            } catch (Exception e) {
                log.error("Failed to expire hold booking id={}: {}", hold.getId(), e.getMessage());
            }
        }
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void expireHold(Long bookingId, Instant now) {
        Booking b = bookingRepository.findByIdForUpdate(bookingId).orElse(null);
        if (b == null) return;

        if (b.getStatus() == BookingStatus.PENDING_PAYMENT && !b.getExpiresAt().isAfter(now)) {
            b.transitionTo(BookingStatus.EXPIRED, null);
            bookingRepository.save(b);

            BookingStatusHistory history = new BookingStatusHistory(
                    b, BookingStatus.PENDING_PAYMENT.name(), BookingStatus.EXPIRED.name(), null, "SYSTEM", "Payment hold expired");
            bookingStatusHistoryRepository.save(history);

            // If a payment was captured after expiration, auto-refund
            Payment payment = paymentRepository.findByBookingId(bookingId).orElse(null);
            if (payment != null && payment.getStatus() == PaymentStatus.SUCCEEDED) {
                refundService.issueRefund(payment.getId(), b.getTotalAmount(), RefundReason.LATE_PAYMENT, "expire-" + bookingId);
            }

            eventPublisher.publishEvent(new BookingEvent(bookingId, NotificationType.BOOKING_EXPIRED));
            log.info("Booking id={} expired from PENDING_PAYMENT", bookingId);
        }
    }
}
