package com.example.rentals.notification;

public enum NotificationType {
    BOOKING_REQUESTED,
    BOOKING_CONFIRMED,
    BOOKING_DECLINED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    BOOKING_COMPLETED,
    PAYOUT_PAID,
    REFUND_ISSUED,
    REVIEW_REMINDER,
    REVIEW_PUBLISHED,
    LISTING_APPROVED,
    LISTING_REJECTED,
    LISTING_SUSPENDED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    NEW_MESSAGE,
    CHECK_IN_REMINDER
}
